export enum CSharpClassPropertyType {
  Guid = 'Guid',
  String = 'string',
  Boolean = 'bool',
  Datetime = 'DateTime',
  Integer = 'int',
  Float = 'float',
  Long = 'long',
  Decimal = 'decimal',
  Byte = 'byte',
  Char = 'byte',
  Sbyte = 'sbyte',
  'Byte[]' = 'byte[]',
  'List<string>' = 'List<string>',
  'List<int>' = 'List<int>',
  'List<long>' = 'List<long>',
  'List<decimal>' = 'List<decimal>',
  'List<guid>' = 'List<guid>',
  'List<bool>' = 'List<bool>',
  'List<float>' = 'List<float>',
  'List<DateTime>' = 'List<DateTime>'
}
